-- Migration: add_depositos_comprobante
-- Adds comprobante (file upload) fields to the depositos table.
-- Uses CREATE TABLE IF NOT EXISTS + ALTER to be idempotent.

-- 1. Create depositos if it does not exist yet
CREATE TABLE IF NOT EXISTS "depositos" (
  "id_deposito"     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario"      INTEGER,
  "banco_sucursal"  VARCHAR(100),
  "ciudad"          VARCHAR(100),
  "referencia"      VARCHAR(50) UNIQUE NOT NULL,
  "monto"           NUMERIC(10,2) NOT NULL,
  "fecha_deposito"  TIMESTAMP NOT NULL,
  "fecha_registro"  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Add comprobante file fields (skip if already present)
ALTER TABLE "depositos"
  ADD COLUMN IF NOT EXISTS "archivo_url"     VARCHAR(500) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "archivo_nombre"  VARCHAR(255) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "archivo_mime"    VARCHAR(100) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "archivo_tamanio" INTEGER      NOT NULL DEFAULT 0;

-- 3. Drop the DEFAULT constraints now that the columns are populated
ALTER TABLE "depositos"
  ALTER COLUMN "archivo_url"     DROP DEFAULT,
  ALTER COLUMN "archivo_nombre"  DROP DEFAULT,
  ALTER COLUMN "archivo_mime"    DROP DEFAULT,
  ALTER COLUMN "archivo_tamanio" DROP DEFAULT;

-- 4. Add FK to usuarios if not present
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'depositos_id_usuario_fkey'
      AND table_name = 'depositos'
  ) THEN
    ALTER TABLE "depositos"
      ADD CONSTRAINT "depositos_id_usuario_fkey"
      FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id_usuario")
      ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
  END IF;
END;
$$;
