-- ==========================================
-- 1. CATÁLOGOS BASE
-- ==========================================

CREATE TABLE cargos (
    id_cargo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR(50) NOT NULL
);

CREATE TABLE estados (
    id_entidad_federativa INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL
);

CREATE TABLE instituciones (
    id_institucion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    abreviatura VARCHAR(30)
);

CREATE TABLE tipo_actividad (
    id_tipo_actividad INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR(50) NOT NULL
);

CREATE TABLE tipo_usuario (
    id_tipo_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR(50) NOT NULL
);

CREATE TABLE titulos (
    id_titulo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR(50) NOT NULL
);

-- ==========================================
-- 2. ENTIDADES PRINCIPALES Y AUTENTICACIÓN
-- ==========================================

-- Se extrajo 'id_costo' hacia la tabla de pagos/recibos, 
-- y se eliminó 'institucion' (texto) para usar solo la llave foránea.
CREATE TABLE usuarios (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folio_recibo VARCHAR(15) UNIQUE,
    codigo_barras VARCHAR(50) UNIQUE,
    nombre VARCHAR(125) NOT NULL,
    apellido VARCHAR(256) NOT NULL,
    correo VARCHAR(100) UNIQUE NOT NULL,
    telefono VARCHAR(20),
    lada VARCHAR(10),
    extension VARCHAR(10),
    genero CHAR(1),
    carrera VARCHAR(128),
    dependencia VARCHAR(128),
    id_cargo INTEGER REFERENCES cargos(id_cargo) ON DELETE SET NULL,
    id_tipo_usuario INTEGER REFERENCES tipo_usuario(id_tipo_usuario) ON DELETE SET NULL,
    id_institucion INTEGER REFERENCES instituciones(id_institucion) ON DELETE SET NULL,
    id_entidad_federativa INTEGER REFERENCES estados(id_entidad_federativa) ON DELETE SET NULL,
    verificado BOOLEAN DEFAULT FALSE,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE accesos (
    id_acceso INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    rol VARCHAR(20) DEFAULT 'USER'
);

-- ==========================================
-- 3. ACTIVIDADES, TALLERES Y HACKATON
-- ==========================================

CREATE TABLE actividades (
    id_actividad INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(200) NOT NULL,
    descripcion TEXT,
    cupo_maximo INTEGER DEFAULT 0,
    fecha_inicio TIMESTAMP NOT NULL,
    fecha_fin TIMESTAMP NOT NULL,
    id_tipo_actividad INTEGER REFERENCES tipo_actividad(id_tipo_actividad) ON DELETE RESTRICT,
    id_institucion_sede INTEGER REFERENCES instituciones(id_institucion) ON DELETE SET NULL,
    id_sala INTEGER DEFAULT 0
);

-- Corrección 1FN: Tabla pivote para múltiples ponentes por actividad
CREATE TABLE actividad_ponentes (
    id_actividad INTEGER REFERENCES actividades(id_actividad) ON DELETE CASCADE,
    id_usuario_ponente INTEGER REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    PRIMARY KEY (id_actividad, id_usuario_ponente)
);

CREATE TABLE talleres (
    id_taller INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_taller VARCHAR(150) NOT NULL,
    cupo_maximo INTEGER DEFAULT 0,
    horario_texto VARCHAR(50), 
    dias_semana VARCHAR(50),
    id_institucion_imparte INTEGER REFERENCES instituciones(id_institucion) ON DELETE SET NULL
);

-- Corrección 1FN: Separación de Equipo y Participantes del Hackaton
CREATE TABLE hackatones (
    id_hackaton INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_equipo VARCHAR(125) NOT NULL,
    id_institucion INTEGER REFERENCES instituciones(id_institucion) ON DELETE SET NULL,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE hackaton_participantes (
    id_participante INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_hackaton INTEGER REFERENCES hackatones(id_hackaton) ON DELETE CASCADE,
    nombre_completo VARCHAR(150) NOT NULL,
    email VARCHAR(100) NOT NULL,
    es_representante BOOLEAN DEFAULT FALSE
);

-- ==========================================
-- 4. INSCRIPCIONES Y ASISTENCIA (Consolidadas)
-- ==========================================

CREATE TABLE inscripcion_actividades (
    id_inscripcion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    id_actividad INTEGER REFERENCES actividades(id_actividad) ON DELETE CASCADE,
    fecha_inscripcion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(id_usuario, id_actividad)
);

CREATE TABLE inscripcion_talleres (
    id_inscripcion_taller INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    id_taller INTEGER REFERENCES talleres(id_taller) ON DELETE CASCADE,
    folio_recibo VARCHAR(20) NOT NULL,
    UNIQUE(id_usuario, id_taller)
);

-- Se elimina la duplicidad de tablas de asistencia
CREATE TABLE asistencia_actividades (
    id_asistencia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    id_actividad INTEGER REFERENCES actividades(id_actividad) ON DELETE CASCADE,
    fecha_hora_marcaje TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(id_usuario, id_actividad)
);

-- ==========================================
-- 5. FINANZAS Y PAGOS
-- ==========================================

CREATE TABLE depositos (
    id_deposito INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    banco_sucursal VARCHAR(100),
    ciudad VARCHAR(100),
    referencia VARCHAR(50) UNIQUE NOT NULL,
    monto NUMERIC(10, 2) NOT NULL,
    fecha_deposito TIMESTAMP NOT NULL,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE facturaciones (
    id_facturacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    razon_social VARCHAR(150) NOT NULL,
    rfc VARCHAR(20) NOT NULL,
    calle VARCHAR(100),
    num_exterior VARCHAR(20),
    num_interior VARCHAR(20),
    colonia VARCHAR(100),
    municipio VARCHAR(100),
    codigo_postal VARCHAR(10),
    id_entidad_federativa_rfc INTEGER REFERENCES estados(id_entidad_federativa) ON DELETE SET NULL
);