CREATE TABLE "cargos" (
  "id_cargo" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" "VARCHAR(50)" NOT NULL
);

CREATE TABLE "estados" (
  "id_entidad_federativa" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" "VARCHAR(50)" NOT NULL
);

CREATE TABLE "instituciones" (
  "id_institucion" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" "VARCHAR(150)" NOT NULL,
  "abreviatura" "VARCHAR(30)"
);

CREATE TABLE "tipo_actividad" (
  "id_tipo_actividad" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" "VARCHAR(50)" NOT NULL
);

CREATE TABLE "tipo_usuario" (
  "id_tipo_usuario" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" "VARCHAR(50)" NOT NULL
);

CREATE TABLE "titulos" (
  "id_titulo" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" "VARCHAR(50)" NOT NULL
);

CREATE TABLE "usuarios" (
  "id_usuario" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "folio_recibo" "VARCHAR(15)" UNIQUE,
  "codigo_barras" "VARCHAR(50)" UNIQUE,
  "nombre" "VARCHAR(125)" NOT NULL,
  "apellido" "VARCHAR(256)" NOT NULL,
  "correo" "VARCHAR(100)" UNIQUE NOT NULL,
  "telefono" "VARCHAR(20)",
  "lada" "VARCHAR(10)",
  "extension" "VARCHAR(10)",
  "genero" "CHAR(1)",
  "carrera" "VARCHAR(128)",
  "dependencia" "VARCHAR(128)",
  "id_cargo" INTEGER,
  "id_tipo_usuario" INTEGER,
  "id_institucion" INTEGER,
  "id_entidad_federativa" INTEGER,
  "verificado" BOOLEAN DEFAULT false,
  "fecha_registro" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "accesos" (
  "id_acceso" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" INTEGER,
  "username" "VARCHAR(50)" UNIQUE NOT NULL,
  "password_hash" "VARCHAR(255)" NOT NULL,
  "rol" "VARCHAR(20)" DEFAULT 'USER'
);

CREATE TABLE "actividades" (
  "id_actividad" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" "VARCHAR(200)" NOT NULL,
  "descripcion" TEXT,
  "cupo_maximo" INTEGER DEFAULT 0,
  "fecha_inicio" TIMESTAMP NOT NULL,
  "fecha_fin" TIMESTAMP NOT NULL,
  "id_tipo_actividad" INTEGER,
  "id_institucion_sede" INTEGER,
  "id_sala" INTEGER DEFAULT 0
);

CREATE TABLE "actividad_ponentes" (
  "id_actividad" INTEGER,
  "id_usuario_ponente" INTEGER,
  PRIMARY KEY ("id_actividad", "id_usuario_ponente")
);

CREATE TABLE "talleres" (
  "id_taller" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_taller" "VARCHAR(150)" NOT NULL,
  "cupo_maximo" INTEGER DEFAULT 0,
  "horario_texto" "VARCHAR(50)",
  "dias_semana" "VARCHAR(50)",
  "id_institucion_imparte" INTEGER
);

CREATE TABLE "hackatones" (
  "id_hackaton" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_equipo" "VARCHAR(125)" NOT NULL,
  "id_institucion" INTEGER,
  "fecha_registro" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "hackaton_participantes" (
  "id_participante" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_hackaton" INTEGER,
  "nombre_completo" "VARCHAR(150)" NOT NULL,
  "email" "VARCHAR(100)" NOT NULL,
  "es_representante" BOOLEAN DEFAULT false
);

CREATE TABLE "inscripcion_actividades" (
  "id_inscripcion" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" INTEGER,
  "id_actividad" INTEGER,
  "fecha_inscripcion" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "inscripcion_talleres" (
  "id_inscripcion_taller" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" INTEGER,
  "id_taller" INTEGER,
  "folio_recibo" "VARCHAR(20)" NOT NULL
);

CREATE TABLE "asistencia_actividades" (
  "id_asistencia" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" INTEGER,
  "id_actividad" INTEGER,
  "fecha_hora_marcaje" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "depositos" (
  "id_deposito" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" INTEGER,
  "banco_sucursal" "VARCHAR(100)",
  "ciudad" "VARCHAR(100)",
  "referencia" "VARCHAR(50)" UNIQUE NOT NULL,
  "monto" "NUMERIC(10,2)" NOT NULL,
  "fecha_deposito" TIMESTAMP NOT NULL,
  "archivo_url" "VARCHAR(500)" NOT NULL,
  "archivo_nombre" "VARCHAR(255)" NOT NULL,
  "archivo_mime" "VARCHAR(100)" NOT NULL,
  "archivo_tamanio" INTEGER NOT NULL,
  "fecha_registro" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "facturaciones" (
  "id_facturacion" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" INTEGER,
  "razon_social" "VARCHAR(150)" NOT NULL,
  "rfc" "VARCHAR(20)" NOT NULL,
  "calle" "VARCHAR(100)",
  "num_exterior" "VARCHAR(20)",
  "num_interior" "VARCHAR(20)",
  "colonia" "VARCHAR(100)",
  "municipio" "VARCHAR(100)",
  "codigo_postal" "VARCHAR(10)",
  "id_entidad_federativa_rfc" INTEGER
);

CREATE UNIQUE INDEX ON "inscripcion_actividades" ("id_usuario", "id_actividad");

CREATE UNIQUE INDEX ON "inscripcion_talleres" ("id_usuario", "id_taller");

CREATE UNIQUE INDEX ON "asistencia_actividades" ("id_usuario", "id_actividad");

ALTER TABLE "usuarios" ADD FOREIGN KEY ("id_cargo") REFERENCES "cargos" ("id_cargo") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "usuarios" ADD FOREIGN KEY ("id_tipo_usuario") REFERENCES "tipo_usuario" ("id_tipo_usuario") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "usuarios" ADD FOREIGN KEY ("id_institucion") REFERENCES "instituciones" ("id_institucion") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "usuarios" ADD FOREIGN KEY ("id_entidad_federativa") REFERENCES "estados" ("id_entidad_federativa") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "accesos" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id_usuario") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "actividades" ADD FOREIGN KEY ("id_tipo_actividad") REFERENCES "tipo_actividad" ("id_tipo_actividad") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "actividades" ADD FOREIGN KEY ("id_institucion_sede") REFERENCES "instituciones" ("id_institucion") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "actividad_ponentes" ADD FOREIGN KEY ("id_actividad") REFERENCES "actividades" ("id_actividad") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "actividad_ponentes" ADD FOREIGN KEY ("id_usuario_ponente") REFERENCES "usuarios" ("id_usuario") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "talleres" ADD FOREIGN KEY ("id_institucion_imparte") REFERENCES "instituciones" ("id_institucion") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "hackatones" ADD FOREIGN KEY ("id_institucion") REFERENCES "instituciones" ("id_institucion") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "hackaton_participantes" ADD FOREIGN KEY ("id_hackaton") REFERENCES "hackatones" ("id_hackaton") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inscripcion_actividades" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id_usuario") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inscripcion_actividades" ADD FOREIGN KEY ("id_actividad") REFERENCES "actividades" ("id_actividad") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inscripcion_talleres" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id_usuario") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inscripcion_talleres" ADD FOREIGN KEY ("id_taller") REFERENCES "talleres" ("id_taller") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "asistencia_actividades" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id_usuario") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "asistencia_actividades" ADD FOREIGN KEY ("id_actividad") REFERENCES "actividades" ("id_actividad") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "depositos" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id_usuario") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "facturaciones" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id_usuario") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "facturaciones" ADD FOREIGN KEY ("id_entidad_federativa_rfc") REFERENCES "estados" ("id_entidad_federativa") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
