-- ==========================================
-- SEED DATA — aniei2026
-- Datos iniciales de catálogos migrados del
-- sistema legacy (cnciic_aniei) + datos de
-- ejemplo para tablas operativas.
-- ==========================================

BEGIN;

-- ==========================================
-- 1. CATÁLOGOS: cargos
-- ==========================================
INSERT INTO cargos (id_cargo, descripcion) VALUES
(1, 'Alumno'),
(2, 'Profesor'),
(3, 'Secretario/Subdirector'),
(4, 'Jefe de Departamento'),
(5, 'Director'),
(6, 'Otro');

-- ==========================================
-- 2. CATÁLOGOS: estados (Entidades Federativas)
-- ==========================================
INSERT INTO estados (id_entidad_federativa, nombre) VALUES
(1,  'Aguascalientes'),
(2,  'Baja California'),
(3,  'Baja California Sur'),
(4,  'Campeche'),
(5,  'Chiapas'),
(6,  'Chihuahua'),
(7,  'Coahuila'),
(8,  'Colima'),
(9,  'Ciudad de México'),
(10, 'Durango'),
(11, 'Estado de México'),
(12, 'Guanajuato'),
(13, 'Guerrero'),
(14, 'Hidalgo'),
(15, 'Jalisco'),
(16, 'Michoacán'),
(17, 'Morelos'),
(18, 'Nayarit'),
(19, 'Nuevo León'),
(20, 'Oaxaca'),
(21, 'Puebla'),
(22, 'Querétaro'),
(23, 'Quintana Roo'),
(24, 'San Luis Potosí'),
(25, 'Sinaloa'),
(26, 'Sonora'),
(27, 'Tabasco'),
(28, 'Tamaulipas'),
(29, 'Tlaxcala'),
(30, 'Veracruz'),
(31, 'Yucatán'),
(32, 'Zacatecas');

-- ==========================================
-- 3. CATÁLOGOS: tipo_usuario
-- ==========================================
INSERT INTO tipo_usuario (id_tipo_usuario, descripcion) VALUES
(1, 'Alumno'),
(2, 'Académico'),
(3, 'Directivo'),
(4, 'Instructor'),
(5, 'Ponente'),
(6, 'Externo');

-- ==========================================
-- 4. CATÁLOGOS: tipo_actividad
-- ==========================================
INSERT INTO tipo_actividad (id_tipo_actividad, descripcion) VALUES
(1,  'Taller'),
(2,  'Seminario'),
(3,  'Conferencia Magistral'),
(4,  'Conferencia Simultánea'),
(5,  'Videoconferencia'),
(6,  'Mesa de Trabajo'),
(7,  'Concurso'),
(8,  'Ponencia'),
(9,  'Tesis'),
(10, 'Conferencia Invitada'),
(11, 'Hackatón'),
(12, 'Certificación'),
(13, 'Inauguración');

-- ==========================================
-- 5. CATÁLOGOS: titulos
-- ==========================================
INSERT INTO titulos (id_titulo, descripcion) VALUES
(1, 'Bachillerato'),
(2, 'Pasante'),
(3, 'Licenciatura'),
(4, 'Maestro'),
(5, 'Ingeniero'),
(6, 'Doctorado');

-- ==========================================
-- 6. CATÁLOGOS: instituciones
-- ==========================================
INSERT INTO instituciones (id_institucion, nombre, abreviatura) VALUES
(1,   'Benemérita Universidad Autónoma de Puebla', 'BUAP'),
(2,   'Centro Cultural Universitario Justo Sierra', 'CCUJS'),
(3,   'Centro de Enseñanza Técnica y Superior', 'CETYS'),
(4,   'Centro de Estudio de Alta Dirección', 'CEAD'),
(5,   'Centro de Estudios Básicos y Superiores del Sureste S.C.', 'CEBSS'),
(6,   'Centro de Estudios Científicos y Tecnológicos 14', 'CECyT 14'),
(7,   'Centro de Estudios Científicos y Tecnológicos 9', 'CECyT 9'),
(8,   'Centro de Estudios Superiores CTM', 'CESCTM'),
(9,   'Centro de Estudios Superiores del Estado de Sonora', 'CESES'),
(10,  'Centro de Investigación en Computación IPN', 'CIC'),
(11,  'Centro Universitario de Coatzacoalcos', 'CUCOATZA'),
(12,  'Centro Universitario Hispanoamericano S.C.', 'CUHISPANO'),
(13,  'CONALEP Guanajuato', 'CONALEP GTO'),
(14,  'CONALEP San Luis Potosí', 'CONALEP SLP'),
(15,  'CONALEP Jalisco', 'CONALEP JAL'),
(16,  'CONALEP Estado de México', 'CONALEP EDO'),
(17,  'CONALEP Tlalpan 1', 'CONALEP TL'),
(18,  'Conjunto Educativo S.C.', 'CE'),
(19,  'Dirección General de Educación Tecnológica Industrial', 'DGETI'),
(20,  'Escuela Normal Rural Justo Sierra Méndez', 'SECYD'),
(21,  'Escuela Superior de Cómputo IPN', 'ESCOM'),
(22,  'Fundación Arturo Rosenblueth', 'FAR'),
(23,  'Instituto Artek', 'ARTEK'),
(24,  'Instituto de Ciencias y Estudios Superiores de Tamaulipas A.C.', 'ICEST'),
(25,  'Instituto de Estudios Superiores de Chiapas', 'IESCH'),
(26,  'Instituto de Estudios Superiores de Monterrey Campus Querétaro', 'ITESM QRO'),
(27,  'Instituto de Estudios Superiores de Tamaulipas A.C.', 'IEST'),
(28,  'Instituto Educativo del Noreste A.C.', 'CETYS'),
(29,  'Instituto Galileo de Coatzacoalcos', 'CEUNICO'),
(30,  'Instituto Nacional de Astrofísica, Óptica y Electrónica', 'INAOE'),
(31,  'Instituto Politécnico Nacional (CINVESTAV)', 'CINVESTAV'),
(32,  'Instituto Politécnico Nacional (UPIICSA)', 'UPIICSA'),
(33,  'Instituto Politécnico Nacional (CIC)', 'IPN CIC'),
(34,  'Instituto Politécnico Nacional (ESCOM)', 'IPN ESCOM'),
(35,  'Instituto Politécnico Nacional (CECyT 9)', 'IPN CECyT9'),
(36,  'Instituto Politécnico Nacional (CECyT 14)', 'IPN CECyT14'),
(37,  'Instituto Tecnológico Autónomo de México', 'ITAM'),
(38,  'Instituto Tecnológico de Acapulco', 'IT Acapulco'),
(39,  'Instituto Tecnológico de Aguascalientes', 'IT Ags'),
(40,  'Instituto Tecnológico de Apizaco', 'IT Apizaco'),
(41,  'Instituto Tecnológico de Cancún', 'IT Cancún'),
(42,  'Instituto Tecnológico de Ciudad Valles', 'IT Cd Valles'),
(43,  'Instituto Tecnológico de Celaya', 'IT Celaya'),
(44,  'Instituto Tecnológico de Cerro Azul', 'IT Cerro Azul'),
(45,  'Instituto Tecnológico de Chetumal', 'IT Chetumal'),
(46,  'Instituto Tecnológico de Chihuahua II', 'IT Chih II'),
(47,  'Instituto Tecnológico de Ciudad Guzmán', 'IT Cd Guzmán'),
(48,  'Instituto Tecnológico de Ciudad Juárez', 'IT Cd Juárez'),
(49,  'Instituto Tecnológico de Coatzacoalcos', 'IT Coatz'),
(50,  'Instituto Tecnológico de Comitán', 'IT Comitán'),
(51,  'Instituto Tecnológico de Culiacán', 'IT Culiacán'),
(52,  'Instituto Tecnológico de Estudios Superiores de la Región Carbonífera', 'ITESRC'),
(53,  'Instituto Tecnológico de Estudios Superiores de Zamora', 'ITESZ'),
(54,  'Instituto Tecnológico de Iguala', 'IT Iguala'),
(55,  'Instituto Tecnológico de Jiquilpan', 'IT Jiquilpan'),
(56,  'Instituto Tecnológico de la Laguna', 'IT Laguna'),
(57,  'Instituto Tecnológico de La Paz', 'IT La Paz'),
(58,  'Instituto Tecnológico de Lázaro Cárdenas', 'IT Lázaro C'),
(59,  'Instituto Tecnológico de León', 'IT León'),
(60,  'Instituto Tecnológico de Los Mochis', 'IT Los Mochis'),
(61,  'Instituto Tecnológico de Matamoros', 'IT Matamoros'),
(62,  'Instituto Tecnológico de Mérida', 'IT Mérida'),
(63,  'Instituto Tecnológico de Morelia', 'IT Morelia'),
(64,  'Instituto Tecnológico de Puebla', 'IT Puebla'),
(65,  'Instituto Tecnológico de Puerto Vallarta', 'IT Pto Vallarta'),
(66,  'Instituto Tecnológico de Querétaro', 'IT Querétaro'),
(67,  'Instituto Tecnológico de San Luis Potosí', 'IT SLP'),
(68,  'Instituto Tecnológico de Tehuacán', 'IT Tehuacán'),
(69,  'Instituto Tecnológico de Tepic', 'IT Tepic'),
(70,  'Instituto Tecnológico de Tijuana', 'IT Tijuana'),
(71,  'Instituto Tecnológico de Tlalnepantla', 'IT Tlalnepantla'),
(72,  'Instituto Tecnológico de Zacatecas Norte', 'IT Zac Norte'),
(73,  'Instituto Tecnológico de Zitácuaro', 'IT Zitácuaro'),
(74,  'Instituto Tecnológico del Sur de Guanajuato', 'IT Sur Gto'),
(75,  'Instituto Tecnológico Latinoamericano', 'ITLAT'),
(76,  'Instituto Tecnológico Superior de Acatlán de Osorio', 'ITS Acatlán'),
(77,  'Instituto Tecnológico Superior de Acayucan', 'ITS Acayucan'),
(78,  'Instituto Tecnológico Superior de Alvarado', 'ITS Alvarado'),
(79,  'Instituto Tecnológico Superior de Arandas', 'ITS Arandas'),
(80,  'Instituto Tecnológico Superior de Atlixco', 'ITS Atlixco'),
(81,  'Instituto Tecnológico Superior de Centla', 'ITS Centla'),
(82,  'Instituto Tecnológico Superior de Coatzacoalcos', 'ITS Coatz'),
(83,  'Instituto Tecnológico Superior de Huichapan', 'ITS Huichapan'),
(84,  'Instituto Tecnológico Superior de Irapuato', 'ITS Irapuato'),
(85,  'Instituto Tecnológico Superior de Libres', 'ITS Libres'),
(86,  'Instituto Tecnológico Superior de Los Reyes', 'ITS Los Reyes'),
(87,  'Instituto Tecnológico Superior de Misantla', 'ITS Misantla'),
(88,  'Instituto Tecnológico Superior de Puerto Vallarta', 'ITS Pto Vallarta'),
(89,  'Instituto Tecnológico Superior de Tepeaca', 'ITS Tepeaca'),
(90,  'Instituto Tecnológico Superior de Tepexi de Rodríguez', 'ITS Tepexi'),
(91,  'Instituto Tecnológico Superior de Uruapan', 'ITS Uruapan'),
(92,  'Instituto Tecnológico Superior de Zacatecas Norte', 'ITS Zac Norte'),
(93,  'Instituto Tecnológico Superior de Zapotlanejo', 'ITS Zapotlanejo'),
(94,  'Instituto Tecnológico Superior del Sur de Guanajuato', 'ITS Sur Gto'),
(95,  'Instituto Tecnológico Superior El Grullo', 'ITS El Grullo'),
(96,  'ITESM Campus Querétaro', 'ITESM QRO'),
(97,  'ITESM Campus Estado de México', 'ITESM CEM'),
(98,  'ITESM Campus Ciudad de México', 'ITESM CDMX'),
(99,  'ITESM Campus Monterrey', 'ITESM MTY'),
(100, 'Instituto Tecnológico y de Estudios Superiores de Occidente', 'ITESO'),
(101, 'Universidad IUEM', 'IUEM'),
(102, 'Laboratorio Nacional de Informática Avanzada', 'LANIA'),
(103, 'Latinoamericana de Ciencias y Tecnología A.C.', 'ITLAT'),
(104, 'Universidad del Golfo de México A.C.', 'UGM'),
(105, 'Sun Microsystems de México S.A. de C.V.', 'SUN'),
(106, 'Tecnológico de Estudios Superiores de Coacalco', 'TESCO'),
(107, 'Tecnológico de Estudios Superiores de Cuautitlán Izcalli', 'TESCI'),
(108, 'Tecnológico de Estudios Superiores de Ecatepec', 'TESE'),
(109, 'Universidad Americana de Acapulco', 'UAA Acapulco'),
(110, 'Universidad Autónoma de Aguascalientes', 'UAA'),
(111, 'Universidad Autónoma de Baja California', 'UABC'),
(112, 'Universidad Autónoma de Baja California Sur', 'UABCS'),
(113, 'Universidad Autónoma de Campeche', 'UAC'),
(114, 'Universidad Autónoma de Chiapas', 'UNACH'),
(115, 'Universidad Autónoma de Chihuahua', 'UACH'),
(116, 'Universidad Autónoma de Ciudad Juárez', 'UACJ'),
(117, 'Universidad Autónoma de Coahuila', 'UAdeC'),
(118, 'Universidad Autónoma de Guadalajara Campus Tabasco', 'UAG Tab'),
(119, 'Universidad Autónoma de Guerrero', 'UAGro'),
(120, 'Universidad Autónoma de la Laguna A.C.', 'UAL'),
(121, 'Universidad Autónoma de Nayarit', 'UAN'),
(122, 'Universidad Autónoma de Nuevo León (FCFM)', 'UANL FCFM'),
(123, 'Universidad Autónoma de Nuevo León (FIME)', 'UANL FIME'),
(124, 'Universidad Autónoma de Querétaro', 'UAQ'),
(125, 'Universidad Autónoma de Sinaloa', 'UAS'),
(126, 'Universidad Autónoma de Tamaulipas', 'UAT'),
(127, 'Universidad Autónoma de Yucatán', 'UADY'),
(128, 'Universidad Autónoma del Carmen', 'UNACAR'),
(129, 'Universidad Autónoma del Estado de Hidalgo', 'UAEH'),
(130, 'Universidad Autónoma del Estado de México', 'UAEMex'),
(131, 'Universidad Autónoma del Estado de Morelos', 'UAEMor'),
(132, 'Universidad Autónoma del Noreste A.C.', 'UANE'),
(133, 'Universidad Autónoma Metropolitana', 'UAM'),
(134, 'Universidad de Colima (FCYA Manzanillo)', 'UCol Manz'),
(135, 'Universidad de Colima (Facultad de Telemática)', 'UCol Tele'),
(136, 'Universidad de Cuautitlán Izcalli', 'UCI'),
(137, 'Universidad de Guadalajara (CC)', 'UdG CC'),
(138, 'Universidad de Guadalajara (CUALTOS)', 'UdG CUALTOS'),
(139, 'Universidad de Guadalajara (CUC)', 'UdG CUC'),
(140, 'Universidad de Guadalajara (CUCEA)', 'UdG CUCEA'),
(141, 'Universidad de Guadalajara (CUCEI)', 'UdG CUCEI'),
(142, 'Universidad de Guadalajara (CUCIENEGA)', 'UdG CUCIENEGA'),
(143, 'Universidad de Guadalajara (CUNORTE)', 'UdG CUNORTE'),
(144, 'Universidad de Guadalajara (CUSUR)', 'UdG CUSUR'),
(145, 'Universidad de Guadalajara (CUVALLES)', 'UdG CUVALLES'),
(146, 'Universidad de Guanajuato', 'UGto'),
(147, 'Universidad de Ixtlahuaca CUI A.C.', 'UICUI'),
(148, 'Universidad de La Salle Bajío A.C.', 'La Salle Bajío'),
(149, 'Universidad de León', 'U León'),
(150, 'Universidad de Montemorelos', 'U Montemorelos'),
(151, 'Universidad de Monterrey', 'UDEM'),
(152, 'Universidad de Morelia', 'U Morelia'),
(153, 'Universidad de Occidente', 'UdeO'),
(154, 'Universidad de Quintana Roo', 'UQROO'),
(155, 'Universidad de Sonora', 'UNISON'),
(156, 'Universidad de Sotavento A.C.', 'USotavento'),
(157, 'Universidad del Caribe', 'UCar'),
(158, 'Universidad del Mayab', 'UNIMAYAB'),
(159, 'Universidad del Valle de México', 'UVM'),
(160, 'Universidad del Valle de Puebla S.C.', 'UVP'),
(161, 'Universidad Emilio Cárdenas S.C.', 'UEC'),
(162, 'Universidad Estatal de Sonora', 'UES'),
(163, 'Universidad Iberoamericana Campus CDMX', 'IBERO CDMX'),
(164, 'Universidad Iberoamericana Campus Puebla', 'IBERO Puebla'),
(165, 'Universidad Insurgentes S.C.', 'UINSURG'),
(166, 'Universidad Intercontinental', 'UIC'),
(167, 'Universidad Juárez Autónoma de Tabasco (DACB)', 'UJAT DACB'),
(168, 'Universidad Juárez Autónoma de Tabasco (DACyTI)', 'UJAT DACyTI'),
(169, 'Universidad Juárez Autónoma de Tabasco (DAIS)', 'UJAT DAIS'),
(170, 'Universidad La Salle A.C. CDMX', 'La Salle CDMX'),
(171, 'Universidad Latina de América A.C.', 'UNLA'),
(172, 'Universidad Loyola del Pacífico', 'ULP'),
(173, 'Universidad Mesoamericana de San Agustín', 'UMSA'),
(174, 'Universidad México Americana del Norte A.C.', 'UMAN'),
(175, 'Universidad Nacional Autónoma de México (DGTIC)', 'UNAM DGTIC'),
(176, 'Universidad Nacional Autónoma de México (Fac. de Ciencias)', 'UNAM FC'),
(177, 'Universidad Nacional Autónoma de México (FES Cuautitlán)', 'UNAM FES Cuaut'),
(178, 'Universidad Nacional Autónoma de México (FES Acatlán)', 'UNAM FES Acatlán'),
(179, 'Universidad Nacional Autónoma de México (FES Aragón)', 'UNAM FES Aragón'),
(180, 'Universidad Pablo Guardado Chávez S.C.', 'UPGC'),
(181, 'Universidad Panamericana', 'UP'),
(182, 'Universidad Politécnica de Aguascalientes', 'UPA'),
(183, 'Universidad Politécnica de San Luis Potosí', 'UPSLP'),
(184, 'Universidad Politécnica de Zacatecas', 'UPZ'),
(185, 'Universidad Politécnica Metropolitana de Hidalgo', 'UPMH'),
(186, 'Universidad Popular Autónoma del Estado de Puebla', 'UPAEP'),
(187, 'Universidad Regiomontana A.C.', 'UR'),
(188, 'Universidad Regional del Sureste A.C.', 'URSE'),
(189, 'Universidad Simón Bolívar', 'USB'),
(190, 'Universidad Tecnológica Americana', 'UTAM'),
(191, 'Universidad Tecnológica de Calvillo', 'UT Calvillo'),
(192, 'Universidad Tecnológica de Campeche', 'UT Campeche'),
(193, 'Universidad Tecnológica de Cancún', 'UT Cancún'),
(194, 'Universidad Tecnológica de Huejotzingo', 'UT Huejotzingo'),
(195, 'Universidad Tecnológica de Jalisco', 'UT Jalisco'),
(196, 'Universidad Tecnológica de la Mixteca', 'UTM'),
(197, 'Universidad Tecnológica de la Selva', 'UT Selva'),
(198, 'Universidad Tecnológica de la Sierra Hidalguense', 'UTSH'),
(199, 'Universidad Tecnológica de León', 'UT León'),
(200, 'Universidad Tecnológica de Orizaba', 'UT Orizaba'),
(201, 'Universidad Tecnológica de México', 'UNITEC'),
(202, 'Universidad Tecnológica de Morelia', 'UT Morelia'),
(203, 'Universidad Tecnológica de Nezahualcóyotl', 'UT Neza'),
(204, 'Universidad Tecnológica de Puebla', 'UT Puebla'),
(205, 'Universidad Tecnológica de Tabasco', 'UT Tabasco'),
(206, 'Universidad Tecnológica de Tulancingo', 'UT Tulancingo'),
(207, 'Universidad Tecnológica de Tula-Tepeji', 'UTTT'),
(208, 'Universidad Tecnológica de Xicotepec de Juárez', 'UT Xicotepec'),
(209, 'Universidad Tecnológica del Estado de Zacatecas', 'UTEZ'),
(210, 'Universidad Tecnológica del Suroeste de Guanajuato', 'UTSEG'),
(211, 'Universidad Tecnológica del Norte de Aguascalientes', 'UTNA'),
(212, 'Universidad Tecnológica del Norte de Guanajuato', 'UTNG'),
(213, 'Universidad Tecnológica del Valle del Mezquital', 'UTVM'),
(214, 'Universidad Tecnológica Fidel Velázquez', 'UTFV'),
(215, 'Universidad Tecnológica Tula-Tepeji', 'UTTT'),
(216, 'Universidad Valle del Grijalva A.C.', 'UVG'),
(217, 'Universidad Vasco de Quiroga A.C.', 'UVQ'),
(218, 'Universidad Veracruzana (Campus Coatzacoalcos)', 'UV Coatz'),
(219, 'Universidad Veracruzana (Fac. Estadística e Informática)', 'UV FEI'),
(220, 'Universidad de Ixtlahuaca UI-CUI', 'UICUI');

-- ==========================================
-- 7. Resetear secuencias de IDENTITY
--    para que el próximo INSERT automático
--    continúe después del último ID insertado.
-- ==========================================
SELECT setval(pg_get_serial_sequence('cargos', 'id_cargo'), (SELECT MAX(id_cargo) FROM cargos));
SELECT setval(pg_get_serial_sequence('estados', 'id_entidad_federativa'), (SELECT MAX(id_entidad_federativa) FROM estados));
SELECT setval(pg_get_serial_sequence('tipo_usuario', 'id_tipo_usuario'), (SELECT MAX(id_tipo_usuario) FROM tipo_usuario));
SELECT setval(pg_get_serial_sequence('tipo_actividad', 'id_tipo_actividad'), (SELECT MAX(id_tipo_actividad) FROM tipo_actividad));
SELECT setval(pg_get_serial_sequence('titulos', 'id_titulo'), (SELECT MAX(id_titulo) FROM titulos));
SELECT setval(pg_get_serial_sequence('instituciones', 'id_institucion'), (SELECT MAX(id_institucion) FROM instituciones));

COMMIT;
